### ISSUE TITLE
Represent knp menu by yml config

### ISSUE THREAD

**Issue by eddiejaoude** [eddiejaoude/SymfonyQuickStart#1]
Example:

``` php
// ...
   $menu->addChild('nav.home', array('route' => 'quickstart_app_homepage'));
   $menu->addChild('nav.register', array('route' => 'fos_user_registration_register'));
   $menu->addChild('nav.login', array('route' => 'fos_user_security_login'));
// ...
```

Could be expressed in yml config...

``` yml
# ...
menu:
   main:
      nav.home:
         route: quickstart_app_homepage
      nav.register:
         route: fos_user_registration_register
      nav.login:
         route: fos_user_security_login
# ...
```
